@startuml
ParentClass <|-- ChildClass
abstract class ParentClass {
  int field1
  {static} char field2
  {abstract} void methodA()
  double metodB()
}

class ChildClass {
   void methodA()
   {static} void methodC()
}
@enduml