@startuml
participant :Client
-> :Client : work
activate :Client

' :Client -> :Server : open
' activate :Server
' return
' deactivate :Server

' :Client -> :Server : print
' activate :Server
' return
' deactivate :Server

' :Server -> :Device : write
' activate :Device
' return
' deactivate :Device

' :Client -> :Server : close
' activate :Server
' return
' deactivate :Server
@enduml